%%{init: {"flowchart": {"defaultRenderer": "elk"}}}%%
flowchart TD
A(["开始"])
B["STM32 通过 I2C 读取 MPU6050"]
C["STM32 通过 USART 接收 HC05 蓝牙模块"]
D["处理 I2C 数据"]
E["处理 USART 数据"]
F(["结束"])

A --> B
B --> D
A --> C
C --> E
D --> F
E --> F